namespace Accredia.SIGAD.Anagrafiche.Api.V1.Features.Persone.RegistroTrattamenti;

internal sealed record CreateRequest(
    string Codice,
    string NomeTrattamento,
    string? Descrizione,
    int TipoFinalitaTrattamentoId,
    string BaseGiuridica,
    string CategorieDati,
    string CategorieInteressati,
    bool DatiParticolari,
    bool DatiGiudiziari,
    string? CategorieDestinatari,
    bool TrasferimentoExtraUE,
    string? PaesiExtraUE,
    string? GaranzieExtraUE,
    string TermineConservazione,
    int? TermineConservazioneGiorni,
    string? MisureSicurezza,
    int? ResponsabileTrattamentoId,
    int? ContitolareId,
    bool DPONotificato,
    string Stato,
    DateTime DataInizioTrattamento,
    DateTime? DataFineTrattamento);

internal sealed record UpdateRequest(
    string Codice,
    string NomeTrattamento,
    string? Descrizione,
    int TipoFinalitaTrattamentoId,
    string BaseGiuridica,
    string CategorieDati,
    string CategorieInteressati,
    bool DatiParticolari,
    bool DatiGiudiziari,
    string? CategorieDestinatari,
    bool TrasferimentoExtraUE,
    string? PaesiExtraUE,
    string? GaranzieExtraUE,
    string TermineConservazione,
    int? TermineConservazioneGiorni,
    string? MisureSicurezza,
    int? ResponsabileTrattamentoId,
    int? ContitolareId,
    bool DPONotificato,
    string Stato,
    DateTime DataInizioTrattamento,
    DateTime? DataFineTrattamento);

